// Paths shared by astro.config.mjs, the build scripts, and the tests.

/** Original variable font (wght 100–900); never served as-is. */
export const NOTO_SOURCE = "./fonts/noto-sans-jp/NotoSansJP-wght.ttf";

/** Subset generated by scripts/subset-fonts.mjs (git-ignored). */
export const NOTO_SUBSET = "./.generated/fonts/noto-sans-jp.woff2";

/** Characters included in NOTO_SUBSET, for inspection and tests. */
export const NOTO_SUBSET_CHARS = "./.generated/fonts/noto-sans-jp.chars.txt";

/** Set during the first build, which only collects the characters in use. */
export const COLLECT_PASS = process.env.FONT_PASS === "collect";
