// @ts-check
// Paths and settings shared by astro.config.mjs, the build scripts, and the tests.
// Paths are relative to the repository root; the scripts chdir there first.

/** Original variable font (wght 100–900); never served as-is. */
export const NOTO_SOURCE = "./fonts/noto-sans-jp/NotoSansJP-wght.ttf";

/** sha256 recorded in fonts/noto-sans-jp/SOURCE.md; checked before subsetting. */
export const NOTO_SOURCE_SHA256 =
  "c2f3b4d463500a2ddcd3849cded1fceeb9fd6d1c32e6cbecd568453ba50fc68f";

/** Subset generated by scripts/subset-fonts.mjs (git-ignored). */
export const NOTO_SUBSET = "./.generated/fonts/noto-sans-jp.woff2";

/** Characters included in NOTO_SUBSET, for inspection and tests. */
export const NOTO_SUBSET_CHARS = "./.generated/fonts/noto-sans-jp.chars.txt";

/**
 * Which pass of scripts/build.mjs is running: "collect" builds with the original
 * font to find the characters in use, "final" builds with the subset.
 * Unset outside the wrapper (e.g. `astro dev`).
 * @type {"collect" | "final" | undefined}
 */
export const FONT_PASS = (() => {
  const pass = process.env.FONT_PASS;
  if (pass === undefined || pass === "collect" || pass === "final") return pass;
  throw new Error(
    `Unknown FONT_PASS "${pass}" (expected "collect" or "final")`,
  );
})();
